var searchData=
[
  ['fb_0',['fB',['../namespacefun.html#a6dc8c0dc671a2bdeab54aaafdee4e6c5',1,'fun']]],
  ['features_1',['✨ Features',['../index.html#autotoc_md1',1,'']]],
  ['format_2',['Run clang-format',['../index.html#autotoc_md6',1,'']]],
  ['fr_3',['FR',['../namespaceprojgeom.html#a8a30bed9a143598e48475e3316e662f8a11aedd0e432747c2bcd97b82808d24a0',1,'projgeom']]],
  ['fraction_4',['fraction',['../structfun_1_1Fraction.html',1,'fun::Fraction&lt; Z &gt;'],['../structfun_1_1Fraction.html#a49f9c84d9b84ca5fed0e90e5a647f8d4',1,'fun::Fraction::Fraction()'],['../structfun_1_1Fraction.html#a5fb0cd0fa7059f3a5d87ebcc8a3d4ed6',1,'fun::Fraction::Fraction(const Z &amp;num)'],['../structfun_1_1Fraction.html#acd42797b954ae4cb20b67d54288f71e2',1,'fun::Fraction::Fraction(Z &amp;&amp;num)'],['../structfun_1_1Fraction.html#a4bfb5676935284d4c6b3512e5f9b65ec',1,'fun::Fraction::Fraction(Z num, Z den)']]],
  ['fractions_2ehpp_5',['fractions.hpp',['../fractions_8hpp.html',1,'']]],
  ['fun_6',['fun',['../namespacefun.html',1,'']]],
  ['fun_3a_3acayleykleinplane_7',['CayleyKleinPlane',['../conceptfun_1_1CayleyKleinPlane.html',1,'fun']]],
  ['fun_3a_3acayleykleinplanedual_8',['CayleyKleinPlaneDual',['../conceptfun_1_1CayleyKleinPlaneDual.html',1,'fun']]],
  ['fun_3a_3acayleykleinplaneprimitive_9',['CayleyKleinPlanePrimitive',['../conceptfun_1_1CayleyKleinPlanePrimitive.html',1,'fun']]],
  ['fun_3a_3acayleykleinplaneprimitivedual_10',['CayleyKleinPlanePrimitiveDual',['../conceptfun_1_1CayleyKleinPlanePrimitiveDual.html',1,'fun']]],
  ['fun_3a_3aintegral_11',['Integral',['../conceptfun_1_1Integral.html',1,'fun']]],
  ['fun_3a_3aorderedring_12',['OrderedRing',['../conceptfun_1_1OrderedRing.html',1,'fun']]],
  ['fun_3a_3aprojectiveplane_13',['ProjectivePlane',['../conceptfun_1_1ProjectivePlane.html',1,'fun']]],
  ['fun_3a_3aprojectiveplane2_14',['ProjectivePlane2',['../conceptfun_1_1ProjectivePlane2.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanecoord_15',['ProjectivePlaneCoord',['../conceptfun_1_1ProjectivePlaneCoord.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanecoord2_16',['ProjectivePlaneCoord2',['../conceptfun_1_1ProjectivePlaneCoord2.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanecoordh_17',['ProjectivePlaneCoordH',['../conceptfun_1_1ProjectivePlaneCoordH.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanedual_18',['ProjectivePlaneDual',['../conceptfun_1_1ProjectivePlaneDual.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanegeneric_19',['ProjectivePlaneGeneric',['../conceptfun_1_1ProjectivePlaneGeneric.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanegeneric2_20',['ProjectivePlaneGeneric2',['../conceptfun_1_1ProjectivePlaneGeneric2.html',1,'fun']]],
  ['fun_3a_3aprojectiveplanegenerich_21',['ProjectivePlaneGenericH',['../conceptfun_1_1ProjectivePlaneGenericH.html',1,'fun']]],
  ['fun_3a_3aprojectiveplaneh_22',['ProjectivePlaneH',['../conceptfun_1_1ProjectivePlaneH.html',1,'fun']]],
  ['fun_3a_3aprojectiveplaneprim_23',['ProjectivePlanePrim',['../conceptfun_1_1ProjectivePlanePrim.html',1,'fun']]],
  ['fun_3a_3aprojectiveplaneprim2_24',['ProjectivePlanePrim2',['../conceptfun_1_1ProjectivePlanePrim2.html',1,'fun']]],
  ['fun_3a_3aprojectiveplaneprimh_25',['ProjectivePlanePrimH',['../conceptfun_1_1ProjectivePlanePrimH.html',1,'fun']]],
  ['fun_3a_3aprojectiveplaneprimitive_26',['ProjectivePlanePrimitive',['../conceptfun_1_1ProjectivePlanePrimitive.html',1,'fun']]],
  ['fun_3a_3aprojplaneprimdual_27',['ProjPlanePrimDual',['../conceptfun_1_1ProjPlanePrimDual.html',1,'fun']]],
  ['fun_3a_3aring_28',['Ring',['../conceptfun_1_1Ring.html',1,'fun']]],
  ['fun_3a_3asequence_29',['Sequence',['../conceptfun_1_1Sequence.html',1,'fun']]]
];
